import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "../styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/providers/QueryProvider";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevLog",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html
      data-scroll-behavior="smooth"
      lang="en"
      className={`${inter.variable} ${openSans.variable} h-full antialiased dark`}
    >
      <body
        suppressHydrationWarning={true}
        className="min-h-full flex flex-col bg-background text-foreground"
      >
        <Providers>
          <Toaster richColors />
          {children}
        </Providers>
      </body>
    </html>
  );
}
